import express from "express";
import PDFDocument from "pdfkit";
import { createUserClient } from "../lib/supabase.js";

const router = express.Router();

/** GET /api/reports/:caseId — generate a forensic PDF report for a case */
router.get("/:caseId", async (req, res) => {
  const userClient = createUserClient(req.token);
  const { data: c, error } = await userClient
    .from("cases")
    .select("*")
    .eq("id", req.params.caseId)
    .single();

  if (error || !c) return res.status(404).json({ error: "Case not found" });

  const { data: indicators } = await userClient
    .from("indicators")
    .select("*")
    .eq("case_id", req.params.caseId);

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="forensic-report-${c.id}.pdf"`);

  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(res);

  doc.fontSize(18).text("Sentinel — Forensic Investigation Report", { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(9).fillColor("gray").text(`Generated ${new Date().toISOString()}  |  Case ID: ${c.id}`);
  doc.fillColor("black").moveDown(1);

  section(doc, "Email Summary", [
    ["Subject", c.subject || "—"],
    ["From", `${c.from_display_name || ""} <${c.from_address || "—"}>`],
    ["Return-Path", c.return_path || "—"],
    ["Reply-To", c.reply_to || "—"],
    ["Message-ID", c.message_id || "—"],
    ["Sender Domain", c.sender_domain || "—"],
  ]);

  section(doc, "Risk Assessment", [
    ["Category", c.category || "—"],
    ["Fraud Score", `${c.fraud_score ?? "—"} / 100`],
    ["Status", c.status || "open"],
  ]);

  section(doc, "Authentication Results", [
    ["SPF", c.spf_result || "—"],
    ["DKIM", c.dkim_result || "—"],
    ["DMARC", c.dmarc_result || "—"],
  ]);

  section(doc, "Origin Traceability", [
    ["Originating IP", c.origin_ip || "—"],
    ["Country", c.origin_country || "—"],
    ["Region", c.origin_region || "—"],
    ["City", c.origin_city || "—"],
    ["ISP", c.origin_isp || "—"],
    ["Likely Proxy/Hosting", c.is_likely_proxy_or_hosting ? "Yes" : "No"],
    ["Domain Registrar", c.domain_registrar || "—"],
    ["Domain Created", c.domain_created_at || "—"],
  ]);

  doc.fontSize(13).text("Header Anomalies", { underline: true });
  doc.moveDown(0.3);
  const anomalies = c.header_anomalies || [];
  if (anomalies.length === 0) {
    doc.fontSize(10).text("None detected.");
  } else {
    anomalies.forEach((a) => {
      doc.fontSize(10).text(`• [${(a.severity || "").toUpperCase()}] ${a.type}: ${a.detail}`);
    });
  }
  doc.moveDown(1);

  doc.fontSize(13).text("Correlation Indicators", { underline: true });
  doc.moveDown(0.3);
  if (!indicators || indicators.length === 0) {
    doc.fontSize(10).text("None extracted.");
  } else {
    indicators.forEach((i) => {
      doc.fontSize(10).text(`• ${i.type}: ${i.value}`);
    });
  }
  doc.moveDown(1);

  doc.fontSize(8).fillColor("gray").text(
    "Scope note: this report is generated by an automated investigative-lead system. " +
    "Origin geolocation and proxy/hosting flags use free-tier IP intelligence, not commercial " +
    "threat-intel feeds. This output supports investigation and is not a legal attribution.",
    { align: "left" }
  );

  doc.end();
});

function section(doc, title, rows) {
  doc.fontSize(13).fillColor("black").text(title, { underline: true });
  doc.moveDown(0.3);
  rows.forEach(([label, value]) => {
    doc.fontSize(10).text(`${label}: `, { continued: true }).fillColor("gray").text(`${value}`);
    doc.fillColor("black");
  });
  doc.moveDown(1);
}

export default router;
